language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - android-25
before_install:
 - yes | sdkmanager "platforms;android-26"
 - yes | sdkmanager "platforms;android-27"
 - yes | sdkmanager "platforms;android-28"  
jdk:
- oraclejdk8
script:
  - "cd wetweex-lib; ./gradlew uploadArchives"
after_success:
- ".buildscript/deploy_snapshot.sh"
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
  - "$HOME/.m2"
env:
  global:
    - secure: "ac/FWUaaWWmX0Qb7up+DVVThLg3qbPdPLCqMa84c31fR+J0//EJOUfLQo0NU6ppVuh/XoTNiXWWjLyuG8p4BvfS1DIFc8++akOfW5UWpOshGNxDkAPmnIoBH/KZW9Xvzh5IAOuf+sYWKsGyz7VZt7fMH0oOizUHy0VxPTGWG0bsrx4jwQaOxVwSuvbRxkkmPdnXR7Hea1wnq2bUT9JOCRd+oMyb+tKKZRHs/4rym4BzC2JX+d9uNB2KTSSC2L26+UqSS82jAPU9mKJNEIhGokxdvRFT0kT4WJHTNQvRCoiSjHx/WDd4K1eylaLZAeBiwNiifQU83XJ+TM66aJ6zWMdBhPntfWeOdtCV4nXdpyMOt6xFYVqwOiMeS9jfMco2tZ5gMVMDzpbIK3JJ00GJHVmXo41+mFD9HvUVYwPQGkkEqcm3UKgmqXW6qfIp0kzEA94M5+WU+HU+iNiUg/h4YUwnklVCooamaUZVvia/B0m89Rr6lzeqc319DbQRrXslftfkrrjnwgJxwbTCnUYz6jcsrJzIAPTHyymfDxAl45vrDh5ATO3aZnWl2kS/5HJXwAQjGd7CGiaqGUauwdO3tqq7BJL7eNszXsGArUb6+NS15ZP+5rQoLbskhBhMfe9DRstrHnVbA6YWggSr9dV2arWCVN9kiQ5XIBhkd0yym7cM="
    - secure: "QtCfNmbtvRqto4aVjOcEtQ/Zn342uyzvOeo9/yihhacOonmlNwol7Eka5J7ZDT82WqMaHjg4d9fQ42m9gQnmHh3JKRdDFln50murn6KOxy1egUHXkmBzFyO8OqlG+rG0xw66kM0gElj2cLN1N2TQIYb0C7wEA2QADZ3TphHbIV12cmYeMxMw5YVHpdrCpFHmHNYQEms80ggepxRL0960dXDQf5VJj5y5EyHn39oN8TsLJAmeepYagOw2bgtGCAhhXO/PI5aYe9Yyipq3YtYVpgK0XmxYZy0sO16W01e5PSUUOi7QJNSSREn4g7IKW3jZ+CSEXJ7i/PiT16JY56lJjH7MUyfKHAAQu3VlA3CU+GTbzcez6wzKChUNM+vVLBzMVBQa6uqjavGRBkM6kqCVDvrpxOR5UALsOian/U6UzfTCMho47NVdebY03+bqezFmyRf/LC3z3Wmsnj+uTE8VlP0/fByABQAC4ShQ4F3bLv0B7RjBKVz3BTz+PPozzkU8oLwT1Yz18vfdltz0pKEYPSVJH13QFoXWQo1PHYuIzeAsUBOissMcA7CGsafEu+ZtdtQkoMcJ93ncz/6H7hIsxAhZDkv0tAXucmz06cTjVFRq1msSBTXHeqQ1zNqX4klywSOzj/HxZbqmw9cKZeV8L1vb1U5YRuj/DnOP1vaTXwo="

